/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "STM32F446xx.h"

#define ADC1_PIN 0
void adc_init(void);
uint16_t adc_read(void);

int main(void)
{
	uint16_t adc;
	float temp;
	adc_init();//Initialize ADC function

	while(1)
	    {
			adc = adc_read();
			temp = (adc * 3.3f / 4095.0f) * 100.0f; //convert voltage read to temperature

	        printf("TEMPERATURE = %.2f Celsius\n", temp);

	        for(volatile int i=0;i<5000000;i++);  //delay
	    }
}

void adc_init(void)
{
	//Enable GPIOA clock
	GPIOA_CLK_EN();

	//Enable ADC1 clock
	ADC1_CLK_EN();

	/*For configuring GPIOA*/
	//Access MODER Register(analog input for ADC from LM35)
	GPIOA->MODER |= (0x3 << (ADC1_PIN * 2)); //For setting 0th and 1st bit position as 11(analog mode).

	//Access PUPDR Register
	GPIOA->PUPDR &= ~(0x3 << (ADC1_PIN * 2)); //For setting 0th and 1st bit position as 00 for no pullup no pulldown.

	/*For configuring ADC*/
	ADC1->CR2 |= (1 << 10);         // EOC flag at each conversion
	ADC1->CR2 |= (1 << 0);          // ADC Enable
	ADC1->SQR3 = ADC1_PIN;          // channel 0
	ADC1->SMPR2 |= (0x3 << 0);      // 56 cycles sampling time for stable LM35 readings
}

uint16_t adc_read(void)
{
    ADC1->CR2 |= (1 << 30);               // Start conversion(SWSTART)
    while(!(ADC1->SR & (1 << 1)));        // Wait for end of conversion(EOC)
    uint16_t adc_reading = ADC1->DR;         // clear  by reading the ADC_DR data register

    return adc_reading;
}
