/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f446xx.h"
#define LED_PIN         5
#define BUTTON_PIN      13


int main(void)
{
	//Enable GPIOA clock
	GPIOA_CLK_EN();

    //Access MODER Register(output for led)
	GPIOA->MODER &= ~(0x3 << (LED_PIN * 2)); //For setting 10th and 11th position as 00.
	GPIOA->MODER |= (0x1 << (LED_PIN * 2));  //For setting 01 at 11th and 10th position.

	//Access OTYPER Register
	GPIOA->OTYPER &= ~(0x1 << LED_PIN); //0 for push pull

	//Access OSPEEDR Register
	GPIOA->OSPEEDR &= ~(0x3 << (LED_PIN * 2)); //For setting 10th and 11th position as 00.
	GPIOA->OSPEEDR |= (0x1 << (LED_PIN * 2));  //For setting 01 at 11th and 10th position for medium speed.

	//Access PUPDR Register
	GPIOA->PUPDR &= ~(0x3 << (LED_PIN * 2)); //For setting 10th and 11th position as 00 for no pullup no pulldown.

	//For led blinking
	for(;;)
	{
		//Access ODR Register
	    GPIOA->ODR ^= (0x1 << LED_PIN);   //Toggle PA5 LED

	    for(uint32_t i = 0; i < 500000; i++); //Delay
	}

}
