/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>
#include "stm32f446xx.h"
#include "stm32f446xx_gpio_driver.h"

// Delay function
	void delay_ms(uint32_t ms)
	{
	    for(uint32_t i = 0; i < (ms * 1000); i++);
	}

int main(void)
{

/*---------------------------------------TASK-1 CONFIGURATION---------------------------------------*/

	/*----------------LED CONFIGURATION (PA5)----------------*/

	GPIO_Handle_t gpio_led;

	gpio_led . pGPIOx = GPIOA;                                          //Select the GPIO for LED
	gpio_led . GPIO_PinConfig . GPIO_PinNumber = GPIO_PIN_NO_5; 		//Configure the pin number
	gpio_led . GPIO_PinConfig . GPIO_PinMode = GPIO_MODE_OUT;  			//Configure the mode of the pin(in/out)
	gpio_led . GPIO_PinConfig . GPIO_PinSpeed = GPIO_SPEED_FAST;		//Configure the output speed mode
	gpio_led . GPIO_PinConfig . GPIO_PinOPType = GPIO_OP_TYPE_PP ;		//Configure output type as push pull
	gpio_led . GPIO_PinConfig . GPIO_PinPuPdControl = GPIO_NO_PUPD;  	//No pull up No pull down

	GPIO_PeriClockControl(GPIOA, ENABLE);  //Enable peripheral clock for LED
	GPIO_Init(&gpio_led);				   //Initialize GPIOA port pin for gpio_led

	/*----------------BUTTON/SWITCH CONFIGURATION (PC13)----------------*/

	GPIO_Handle_t gpio_button;

	gpio_button . pGPIOx = GPIOC; 									   //Select the GPIO for BUTTON
	gpio_button . GPIO_PinConfig . GPIO_PinNumber = GPIO_PIN_NO_13;    //Configure the pin number
	gpio_button . GPIO_PinConfig . GPIO_PinMode = GPIO_MODE_IN; 	   //Configure the mode of the pin(in/out)
	gpio_button . GPIO_PinConfig . GPIO_PinSpeed = GPIO_SPEED_FAST;	   //Configure the output speed mode
	gpio_button . GPIO_PinConfig . GPIO_PinPuPdControl = GPIO_PIN_PU;  //Configure button in pull up mode

	GPIO_PeriClockControl(GPIOC, ENABLE);	//Enable peripheral clock for Switch/button
	GPIO_Init(&gpio_button);			    //Initialize GPIOC port pin for gpio_button

/*---------------------------------------TASK-2 CONFIGURATION---------------------------------------*/

	/*----------------LED CONFIGURATION (PA6)----------------*/

		GPIO_Handle_t gpio_ext_led1;

		gpio_ext_led1 . pGPIOx = GPIOA; 										//Select the GPIO for LED
		gpio_ext_led1 . GPIO_PinConfig . GPIO_PinNumber = GPIO_PIN_NO_6; 		//Configure the pin number
		gpio_ext_led1 . GPIO_PinConfig . GPIO_PinMode = GPIO_MODE_OUT;  		//Configure the mode of the pin(in/out)
		gpio_ext_led1 . GPIO_PinConfig . GPIO_PinSpeed = GPIO_SPEED_FAST;		//Configure the output speed mode
		gpio_ext_led1 . GPIO_PinConfig . GPIO_PinOPType = GPIO_OP_TYPE_PP ;		//Configure output type as push pull
		gpio_ext_led1 . GPIO_PinConfig . GPIO_PinPuPdControl = GPIO_NO_PUPD;  	//No pull up No pull down

		GPIO_PeriClockControl(GPIOA, ENABLE);  //Enable peripheral clock for external LED 1
		GPIO_Init(&gpio_ext_led1);			   //Initialize GPIOA port pin for gpio_ext_led1

	/*----------------LED CONFIGURATION (PA7)----------------*/

		GPIO_Handle_t gpio_ext_led2;

		gpio_ext_led2 . pGPIOx = GPIOA;                                         //Select the GPIO for LED
		gpio_ext_led2 . GPIO_PinConfig . GPIO_PinNumber = GPIO_PIN_NO_7; 		//Configure the pin number
		gpio_ext_led2 . GPIO_PinConfig . GPIO_PinMode = GPIO_MODE_OUT;  		//Configure the mode of the pin(in/out)
		gpio_ext_led2 . GPIO_PinConfig . GPIO_PinSpeed = GPIO_SPEED_FAST;		//Configure the output speed mode
		gpio_ext_led2 . GPIO_PinConfig . GPIO_PinOPType = GPIO_OP_TYPE_PP ;		//Configure output type as push pull
		gpio_ext_led2 . GPIO_PinConfig . GPIO_PinPuPdControl = GPIO_NO_PUPD;  	//No pull up No pull down

		GPIO_PeriClockControl(GPIOA, ENABLE);  //Enable peripheral clock for external LED 2
		GPIO_Init(&gpio_ext_led2);			   //Initialize GPIOA port pin for gpio_ext_led2

		//Set initial state of external LEDs for alternating blink
		GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_6, GPIO_PIN_SET);   //PA6 LED is set HIGH
		GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_7, GPIO_PIN_RESET); //PA7 LED is set LOW

		while(1)
		    {
			/*---------------------------------------TASK-1 => LED TOGGLE ON BUTTON PRESS---------------------------------------*/

		        // check whether button is ACTIVE LOW (Logic 0 when pressed)
		        if (GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_NO_13) == 0)
		        {
		            delay_ms(40); // Debounce delay to ignore mechanical switch bounce
		            GPIO_ToggleOutputPin(GPIOA, GPIO_PIN_NO_5);  //Toggle the state of LED when button is pressed
		        }

		        /*---------------------------------------TASK-2 => ALTERNATE BLINKING OF LED(250ms each)---------------------------------------*/

		        GPIO_ToggleOutputPin(GPIOA, GPIO_PIN_NO_6);
		        GPIO_ToggleOutputPin(GPIOA, GPIO_PIN_NO_7);

		        delay_ms(250);  //Delay of 250ms for each LED
		    }
}
